<?php
namespace frontend\controllers;

use common\www\BaseController;
use Yii;
class SiteController extends BaseController{
//    public function beforeAction($action){
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }

    /**
     * Displays homepage.
     * @return mixed
     */
    public function actionIndex(){
        echo "hello world!";
        $this->setScript('test');
        return $this->show('test');
    }
}
